# Generated by Django 5.1.7 on 2025-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0002_alter_masterclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
